name: Tamic
favicon: null
layout_spectrum: 0.7501286952756345
typography_spectrum: 0.7881663052830845
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7713980199769139
  lightness: 0.42941539781168103
  saturation: 0.5257706574629992
  rhythmicContrast: 0.5138991053681821
purpose: []
